---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api-oss
spec:
  destination:
    name: api
  sources:
    - name: api-gateway
      action: allow
      partition: default
    - name: web
      action: allow
      partition: default