apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: web
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: web
spec:
  selector:
    app: web
  ports:
    - port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v1
  namespace: web
  labels:
    app: web
    version: v1
    service: fake-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      namespace: web
      labels:
        app: web
        service: fake-service
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'true'
        #consul.hashicorp.com/envoy-extra-args: '--log-level debug --disable-hot-restart'
        consul.hashicorp.com/service-tags: 'v1'
        consul.hashicorp.com/service-meta-version: 'v1'
    spec:
      serviceAccountName: web
      containers:
        - name: web
          image: nicholasjackson/fake-service:v0.26.0
          ports:
            - containerPort: 9091
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9091'
            - name: 'UPSTREAM_URIS'
              #value: 'http://api.api:9091'
              #value: 'http://api.virtual.consul:9091'
              value: 'http://api.service.consul:9091'
              #value: 'http://api.virtual.api.ns.usw2.dc.consul:9091'
              #value: 'http://api.service.api.ns.shared-sameness-group.sg.consul:9091'
            - name: 'NAME'
              value: 'web (default/default)'
            - name: 'MESSAGE'
              value: 'web response'
            - name: 'SERVER_TYPE'
              value: 'http'
            - name: 'TIMING_50_PERCENTILE'
              value: '20ms'
            - name: 'TIMING_90_PERCENTILE'
              value: '30ms'
            - name: 'TIMING_99_PERCENTILE'
              value: '40ms'
            - name: 'TIMING_VARIANCE'
              value: '10'
            - name: 'HTTP_SERVER_READ_TIMEOUT'
              value: '0s'
            - name: 'HTTP_SERVER_WRITE_TIMEOUT'
              value: '0s'
            - name: 'HTTP_CLIENT_APPEND_REQUEST'
              value: 'true'
