apiVersion: v1
kind: ServiceAccount
metadata:
  name: tasky
  namespace: tasky
---
apiVersion: v1
kind: Service
metadata:
  name: tasky
  namespace: tasky
spec:
  selector:
    app: tasky
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
  namespace: tasky
  labels:
    app: tasky
    version: v1
    service: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      namespace: tasky
      labels:
        app: tasky
        service: fake-service
    spec:
      serviceAccountName: tasky
      containers:
        - name: tasky
          #image: joshwolfer/tasky:v1.1
          image: ppresto/tasky:latest
          ports:
            - containerPort: 8080
          env:
            - name: 'MONGODB_URI'
              value: 'mongodb://admin:D0ntHackMePls!@10.15.11.108:27017'
            - name: 'SECRET_KEY'
              value: 'secret123'